### ISSUE TITLE
Exception when executing any funciton importing h_check_area

### ISSUE THREAD

**Issue by siliwan** [jakobklemm/RainbowFuture#1]
Hello friend

When I try to execute something, an error gets thrown that a comment is not a number.

Following line(s) are concerned
https://github.com/jakobklemm/RainbowFuture/blob/178c339ab85305635bd463d964d2839f3f3b65cf/h_check_area.sqf#L1

**Comment by jakobklemm** [comment]
That very much sounds like a you problem. When using SQF help is not a luxury you can rely on.
